apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: chat-app-set
  namespace: argocd

spec:
  generators:
    - list:
        elements:
          - name: mongodb
            path: helm/mongodb
            namespace: chat-app
            wave: "0"

          - name: backend
            path: helm/backend
            namespace: chat-app
            wave: "1"
            image: ramachandrampm/chat-app-backend

          - name: frontend
            path: helm/frontend
            namespace: chat-app
            wave: "2"
            image: ramachandrampm/chat-app-frontend

  template:
    metadata:
      name: "chatapp-{{name}}"
      annotations:
        argocd.argoproj.io/sync-wave: "{{wave}}"

        # Apply only where image exists
        argocd-image-updater.argoproj.io/image-list: "{{name}}={{image}}"
        argocd-image-updater.argoproj.io/{{name}}.update-strategy: newest-build

        # Git write-back (values.yaml mode)
        argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/argocd-image-updater-git-creds
        argocd-image-updater.argoproj.io/write-back-target: helm

        # Helm mapping (IMPORTANT)
        argocd-image-updater.argoproj.io/{{name}}.helm.image-name: image.repository
        argocd-image-updater.argoproj.io/{{name}}.helm.image-tag: image.tag

    spec:
      project: default

      source:
        repoURL: https://github.com/NIKHILMPM/Gitops-project.git
        targetRevision: main
        path: "{{path}}"
        helm:
          valueFiles:
            - values.yaml

      destination:
        server: https://kubernetes.default.svc
        namespace: "{{namespace}}"

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
