replicaCount: 2

labels:
  app: frontend

image:
  repository: ramachandrampm/chat-app-frontend
  tag: v1.0.1
  pullPolicy: IfNotPresent

containerPort: 80

service:
  name: frontend
  port: 80

deployment:
  name: frontend-deployment

env:
  NODE_ENV: production
  BACKEND_URL: https://myapp4.xyz/api

ingress:
  name: chat-app-ingress
  className: nginx
  sslRedirect: "true"
  backendService: backend
  backendPort: 5001
  host: myapp4.xyz
  tlsSecret: chatapp-tls
